### ISSUE TITLE
[Roadmap] - K3ai v3

### ISSUE THREAD

**Issue by alefesta** [kf5i/k3ai-core#89]
K3ai project has been placed on hold for a while due to other activities there were running outside of the project. It's time to revamp the project and make it even more awesome!
In order to start developing here's a short list of things I'd like to add quickly but wanted to check with the K3ai community first.
**K3ai List views**:
- [x] A complete re-write of the list views to provide a better understanding of available plugins and their actual status 
For example (this is markdown so is pretty limited):

**List Plugins**
| Name  | Desc | Type |Version | Status (optional)|
|---|---|---|---|---|
| K3s|K3s is a cluster...|v1.21|Local|-|
|KFP| Kubeflow pipelines is..|v1.3|Kubeflow|Installed|

**K3ai plugin** to support in v3:
- [ ]  Inference
    - [ ]  KfServing
    - [ ]  NVIDIA Triton
    - [ ]  Intel Inference
    - [ ]  TF Serving
    - [ ]  PyTorchServe
- [ ]  Model
    - [x]  Kubeflow pipelines
    - [x]  TF Operator
    - [x]  PyTorch Operator
    - [ ]  ONNX
    - [x]  MXNet
- [ ]  Monitor
    - [x]  Katib
    - [x]  MLFlow
    - [ ]  Seldon Alibi
- [ ]  Experiment
    - [x]  JupyterLab
    - [ ]  Orches
- [x] Kubeflow Full Support
    - [x]  Include each KF component as standalone installable component
More specifically for KF

        | Component | Local Manifests Path | Upstream Revision |
        | - | - | - |
        | Training Operator | apps/training-operator/upstream | [v1.3.0-alpha.2](https://github.com/kubeflow/tf-operator/tree/v1.3.0-alpha.2/manifests) |
        | MPI Operator | apps/mpi-job/upstream | [v0.3.0](https://github.com/kubeflow/mpi-operator/tree/v0.3.0/manifests) |
        | Notebook Controller | apps/jupyter/notebook-controller/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/notebook-controller/config) |
        | Tensorboard Controller | apps/tensorboard/tensorboard-controller/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/tensorboard-controller/config) |
        | Central Dashboard | apps/centraldashboard/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/centraldashboard/manifests) |
        | Profiles + KFAM | apps/profiles/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/profile-controller/config) |
        | PodDefaults Webhook | apps/admission-webhook/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/admission-webhook/manifests) |
        | Jupyter Web App | apps/jupyter/jupyter-web-app/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/crud-web-apps/jupyter/manifests) |
        | Tensorboards Web App | apps/tensorboard/tensorboards-web-app/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/crud-web-apps/tensorboards/manifests) |
        | Volumes Web App | apps/volumes-web-app/upstream | [v1.4-rc.0](https://github.com/kubeflow/kubeflow/tree/v1.4-rc.0/components/crud-web-apps/volumes/manifests) |
        | Katib | apps/katib/upstream | [v0.12.0-rc.0](https://github.com/kubeflow/katib/tree/v0.12.0-rc.0/manifests/v1beta1) |
        | KFServing | apps/kfserving/upstream | [v0.6.0](https://github.com/kubeflow/kfserving/releases/tag/v0.6.0) |
        | Kubeflow Pipelines | apps/pipeline/upstream | [1.7.0](https://github.com/kubeflow/pipelines/tree/1.7.0/manifests/kustomize) |
        | Kubeflow Tekton Pipelines | apps/kfp-tekton/upstream | [v1.0.0](https://github.com/kubeflow/kfp-tekton/tree/v1.0.0/manifests/kustomize) |

**Comment by alfsuse** [comment]
K3ai v1.0.0 has been released on Oct. 31st
